function tensor_inner_product = dtd_mv_gamma_multidim_inner_product(tensor_1, tensor_2)
% function dtd_mv_gamma_multidim_kronecker_product(tensor_1, tensor_2)

% Here tensor_1 is sized [nx,ny,nz,3,3] and tensor_2 is sized [3,3]

[nx,ny,nz,~,~] = size(tensor_1);
tensor_inner_product = zeros([nx,ny,nz]);

tensor_inner_product =   tensor_1(:,:,:,1,1)*tensor_2(1,1) ...
                       + tensor_1(:,:,:,1,2)*tensor_2(1,2) ...
                       + tensor_1(:,:,:,1,3)*tensor_2(1,3) ...
                       + tensor_1(:,:,:,2,1)*tensor_2(2,1) ...
                       + tensor_1(:,:,:,2,2)*tensor_2(2,2) ...
                       + tensor_1(:,:,:,2,3)*tensor_2(2,3) ...
                       + tensor_1(:,:,:,3,1)*tensor_2(3,1) ...
                       + tensor_1(:,:,:,3,2)*tensor_2(3,2) ...
                       + tensor_1(:,:,:,3,3)*tensor_2(3,3);